# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = {
  'control' => {'memory' => '2048', 'cpus' => 2, 'ip' => '100', 'provision' => 'control.sh'},
  'worker1' => {'memory' => '2048', 'cpus' => 1, 'ip' => '111', 'provision' => 'worker.sh'},
  'worker2' => {'memory' => '2048', 'cpus' => 1, 'ip' => '112', 'provision' => 'worker.sh'},
  'storage' => {'memory' => '1024', 'cpus' => 1, 'ip' => '50', 'provision' => 'storage.sh'}
}

Vagrant.configure("2") do |config|

  config.vm.box = "oraclelinux/9"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"
  config.vm.box_check_update = false

  vms.each do |name, conf|
    config.vm.define "#{name}" do |k|
      k.vm.hostname = "#{name}.k8s.local"
      k.vm.network 'private_network', ip: "192.168.56.#{conf['ip']}"
      k.vm.provider 'virtualbox' do |vb|
        vb.name = "#{name}"
        vb.memory = conf['memory']
        vb.cpus = conf['cpus']
      end
      k.vm.provision 'shell', path: "provision/#{conf['provision']}", args: "#{conf['ip']}"
    end
  end

  config.vm.provision 'shell', path: 'provision/provision.sh'
end